[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "iBuild"
version = "1.0.0"
dependencies = [
    "attrdict>=2.0.1",
    "diffusers>=0.32.2",
    "einops>=0.8.0",
    "huggingface_hub>=0.28.1",
    "numpy>=2.2.2",
    "Pillow>=11.1.0",
    "timm>=1.0.14",
    "torch>=2.6.0",
    "torchvision>=0.21.0",
    "tqdm>=4.67.1",
    "transformers>=4.48.2",
    "accelerate",
    "sentencepiece",
    "pyjson5>=1.6.8",
    "sv-ttk>=2.6.0",

    # macOS wheels:
    "llama_cpp_python @ https://github.com/oobabooga/llama-cpp-python-cuBLAS-wheels/releases/download/metal/llama_cpp_python-0.3.7-cp311-cp311-macosx_15_0_arm64.whl ; platform_system == 'Darwin' and platform_release >= '24.0.0' and platform_release < '25.0.0' and python_version == '3.11'",
    "llama_cpp_python @ https://github.com/oobabooga/llama-cpp-python-cuBLAS-wheels/releases/download/metal/llama_cpp_python-0.3.7-cp310-cp310-macosx_15_0_arm64.whl ; platform_system == 'Darwin' and platform_release >= '24.0.0' and platform_release < '25.0.0' and python_version == '3.10'",
    "llama_cpp_python @ https://github.com/oobabooga/llama-cpp-python-cuBLAS-wheels/releases/download/metal/llama_cpp_python-0.3.7-cp311-cp311-macosx_14_0_arm64.whl ; platform_system == 'Darwin' and platform_release >= '23.0.0' and platform_release < '24.0.0' and python_version == '3.11'",
    "llama_cpp_python @ https://github.com/oobabooga/llama-cpp-python-cuBLAS-wheels/releases/download/metal/llama_cpp_python-0.3.7-cp310-cp310-macosx_14_0_arm64.whl ; platform_system == 'Darwin' and platform_release >= '23.0.0' and platform_release < '24.0.0' and python_version == '3.10'",
    "llama_cpp_python @ https://github.com/oobabooga/llama-cpp-python-cuBLAS-wheels/releases/download/metal/llama_cpp_python-0.3.7-cp311-cp311-macosx_13_0_arm64.whl ; platform_system == 'Darwin' and platform_release >= '22.0.0' and platform_release < '23.0.0' and python_version == '3.11'",
    "llama_cpp_python @ https://github.com/oobabooga/llama-cpp-python-cuBLAS-wheels/releases/download/metal/llama_cpp_python-0.3.7-cp310-cp310-macosx_13_0_arm64.whl ; platform_system == 'Darwin' and platform_release >= '22.0.0' and platform_release < '23.0.0' and python_version == '3.10'",

    # Windows wheels:
    "llama_cpp_python_cuda @ https://github.com/oobabooga/llama-cpp-python-cuBLAS-wheels/releases/download/textgen-webui/llama_cpp_python_cuda-0.3.7+cu121-cp311-cp311-win_amd64.whl ; platform_system == 'Windows' and python_version == '3.11'",
    "llama_cpp_python_cuda @ https://github.com/oobabooga/llama-cpp-python-cuBLAS-wheels/releases/download/textgen-webui/llama_cpp_python_cuda-0.3.7+cu121-cp310-cp310-win_amd64.whl ; platform_system == 'Windows' and python_version == '3.10'",
]

[tool.pyright]
typeCheckingMode = "standard"
venv = ".venv"
venvPath = "."

[tool.setuptools.packages.find]
where = ["py-ui"]
